"""Main window size configuration constants."""

DEFAULT_WINDOW_WIDTH = 1200
DEFAULT_WINDOW_HEIGHT = 800
MIN_WINDOW_WIDTH = 200
MIN_WINDOW_HEIGHT = 200
MAX_WINDOW_WIDTH = None
MAX_WINDOW_HEIGHT = None

__all__ = [
    "DEFAULT_WINDOW_WIDTH",
    "DEFAULT_WINDOW_HEIGHT",
    "MIN_WINDOW_WIDTH",
    "MIN_WINDOW_HEIGHT",
    "MAX_WINDOW_WIDTH",
    "MAX_WINDOW_HEIGHT",
]
